### ISSUE TITLE
[Bug]: Millibars missing?

### ISSUE THREAD

**Issue by ben-mckenzie** [sfolador/measures-for-laravel#28]
### What happened?

Millibars are listed as an available unit in the readme, but are not found in the UnitsOfPressure enum. 

### How to reproduce the bug

`Measures::from('100mbar')` returns null

### Package Version

0.1.8

### PHP Version

8.3

### Laravel Version

11

**Comment by sfolador** [comment]
Hi Ben, 

thanks!  
I will fix it as soon as possible.

**Comment by sfolador** [comment]
Closed with release 0.1.9
